// This file is auto-generated by scripts/generate-release-notes.mjs
// Do not edit manually.

export type ReleaseNote = {
  version: string;
  date: string;
  markdown: string;
};

export const releaseNotes: ReleaseNote[] = [
  {
    "version": "3.7.0",
    "date": "2026-05-27",
    "markdown": "### Added\n\n- Experimental Connected Calendar support for Google Calendar.\n- Google Calendar events now sync into the existing app Calendar instead of a separate calendar surface.\n- Google calendar source filtering in the Calendar panel.\n- Connected Accounts panel for signing in with Google and syncing connected calendar data.\n- Local OAuth loopback flow with secure token storage.\n- Calendar OAuth configuration support for release builds.\n- Detailed Google OAuth and sync error messages for easier setup and QA.\n\n### Changed\n\n- Connected Accounts now uses a one-click sign-in flow that waits for browser authorization automatically.\n- Calendar sync success messages now only appear when the returned account state is actually synced.\n- Life Area panels received visual cleanup so summary cards and sections render compactly without excessive scrolling.\n\n### Experimental Access Note\n\n- Google Calendar is the only connected calendar provider enabled for this release.\n- This feature is still experimental and requires a build configured with calendar OAuth credentials.\n- Public builds that are not configured for calendar OAuth disable the affected sign-in buttons.\n- Outlook and Microsoft Teams calendar display remain planned, but are not enabled for this release."
  },
  {
    "version": "3.6.0",
    "date": "2026-05-26",
    "markdown": "### Changed\n\n- Created shared UI components for Life Areas: LoadingState, SummaryCard, and LifeAreaPanelProps type\n- Extracted shared date formatting utilities (formatDate, formatDateTime, formatEur, formatMileage) to lib/dateFormat.ts\n- Normalized panel implementations to use shared LoadingState and SummaryCard components\n- Unified panel props interface across all Life Area panels (Finance, Car, Family, Health, Hobbies)\n- Added comprehensive docs/LIFE_AREAS.md guide for creating new Life Area modules\n- Removed unused custom hooks (useLifeAreaData, useLifeAreaCRUD) that were over-engineered\n- Verified backup count labels are consistent across all life slices (Finance, Car, Family, Health, Hobbies)\n- All 1065 tests pass with no behavior changes\n\n### Added\n\n- docs/LIFE_AREAS.md documentation with step-by-step guide for adding new Life Area modules\n- Shared component library in src/renderer/components/life-areas/ for reusable UI patterns\n- Shared utility library in src/renderer/lib/dateFormat.ts for date and number formatting"
  },
  {
    "version": "3.5.0",
    "date": "2026-05-26",
    "markdown": "### Added\n\n- Hobbies module for tracking personal progress and hobby activities with comprehensive management capabilities\n- Hobby management with categories, descriptions, and status tracking (active/inactive)\n- Hobby session logging with duration, mood, energy levels, and progress ratings\n- Hobby project tracking with milestones, target dates, and completion status\n- Hobby milestone management with descriptions, target dates, and completion tracking\n- Hobby supply tracking with types, costs, purchase dates, and source information\n- Hobbies summary dashboard showing active hobbies, sessions this month, open projects, open milestones, and recent sessions\n- Hobbies data integration with backup system (export, import, preview, reset)\n- Comprehensive test coverage for hobbies service, IPC handlers, renderer components, and backup operations\n- Updated Data Control UI to display Hobbies counts in backup preview and import confirmation dialogs\n\n### Changed\n\n- Added Hobbies tab to Personal module navigation in AssistantShell\n- Updated backup system to include all hobbies-related tables in export/import/preview/reset operations\n- Updated IPC handler payload contract tests to include hobbies channels\n- Updated backup UI types to include Hobbies counts for all five hobbies entities\n- Enhanced reset confirmation dialog to mention hobbies data deletion"
  },
  {
    "version": "3.4.0",
    "date": "2026-05-26",
    "markdown": "### Added\n\n- Health module for tracking personal health information with comprehensive management capabilities\n- Health appointments tracking with type, provider, location, date, time, duration, and status\n- Health medications management with dosage, frequency, route, status, and prescriber information\n- Health symptoms logging with severity tracking and date ranges\n- Health measurements recording for weight, blood pressure, heart rate, temperature, blood sugar, and custom metrics\n- Health obligations tracking for refills, lab tests, vaccinations, screenings, exercise, and custom obligations\n- Health summary dashboard showing upcoming appointments, active medications, active symptoms, recent measurements, and open/overdue obligations\n- Health data integration with backup system (export, import, preview, reset)\n- Comprehensive test coverage for health service, IPC handlers, renderer components, and backup operations\n- Updated Data Control UI to display Health counts in backup preview and import confirmation dialogs\n\n### Changed\n\n- Added Health tab to Personal module navigation in AssistantShell\n- Updated backup system to include all health-related tables in export/import/preview/reset operations\n- Updated IPC handler payload contract tests to include health channels\n- Updated backup UI types to include Health counts for all five health entities\n- Enhanced reset confirmation dialog to mention health data deletion"
  },
  {
    "version": "3.3.0",
    "date": "2026-05-26",
    "markdown": "### Added\n\n- Family module for tracking family members, occasions, and obligations\n- Family member management with contact information and importance flags\n- Family occasions tracking for birthdays, name days, anniversaries, memorials, and custom events\n- Family obligations for calls, visits, messages, gifts, paperwork, and custom tasks\n- Family summary dashboard showing member count, upcoming occasions, and open obligations\n- Family data integration with backup system (export, import, preview, reset)\n- Comprehensive test coverage for family service, IPC handlers, renderer components, and backup operations\n\n### Changed\n\n- Added Family tab to Personal module navigation in AssistantShell\n- Updated backup system to include all family-related tables in export/import/preview/reset operations\n- Updated IPC handler payload contract tests to include family channels\n- Updated backup UI types to include Family counts for all three family entities"
  },
  {
    "version": "3.2.0",
    "date": "2026-05-26",
    "markdown": "### Added\n\n- Finance module for tracking bills and expenses with a bills-first interface\n- Bill management with create, update, delete, and mark as paid operations\n- Expense tracking with create, update, and delete operations\n- Monthly financial summary showing upcoming bills, paid bills, unpaid/overdue bills, total expenses, and committed amounts\n- Bill filtering by status (all, unpaid, paid, overdue, upcoming, this_month)\n- Expense filtering by time period (all, this_month)\n- Finance data integration with backup system (export, import, preview, reset)\n- Comprehensive test coverage for finance service, IPC handlers, renderer components, and backup operations\n\n### Changed\n\n- Polished End-of-Day Review panel to always show explicit \"End-of-Day Review\" heading, even in empty state\n- Improved Data Control panel to display health check and optimization results directly in the panel UI\n- Added accessible labels to icon-only toolbar buttons for Appearance, Data, and AI settings\n- Enhanced release hygiene with validation that Windows releases include all required assets (.exe, .blockmap, latest.yml)\n- Added post-release QA checklist entry for verifying GitHub release assets and installed About version\n\n### Fixed\n\n- Improved accessibility of toolbar controls by adding proper ARIA labels to icon-only buttons"
  },
  {
    "version": "3.2.0",
    "date": "2026-05-26",
    "markdown": "### Added\n\n- Car module for vehicle management with comprehensive tracking capabilities\n- Vehicle management with create, update, and delete operations\n- Fuel entry tracking with odometer updates and automatic vehicle mileage updates\n- Maintenance/repair expense tracking with cost and shop information\n- Recurring car bills (insurance, registration, inspection, road tax) with payment tracking\n- Mileage logging for trip distance tracking\n- Service reminders with odometer and date-based due tracking\n- Car data integration with backup system (export, import, preview, reset)\n- Comprehensive test coverage for car service, IPC handlers, renderer components, and backup operations\n\n### Changed\n\n- Added Car tab to Personal module navigation in AssistantShell\n- Updated backup system to include all car-related tables in export/import/preview/reset operations\n- Updated IPC handler payload contract tests to include car channels"
  },
  {
    "version": "3.3.0",
    "date": "2026-05-26",
    "markdown": "### Added\n\n- Family module for family member management with obligations-first interface\n- Family member management with contact information, relationship tracking, and importance marking\n- Family occasion tracking (birthdays, name days, anniversaries, memorials, custom events) with yearly recurrence\n- Family obligation tracking (calls, visits, messages, gifts, paperwork, custom obligations) with due dates and priority levels\n- Family summary showing total members, important members, upcoming occasions (30 days), open obligations, and overdue obligations\n- Yearly occasion comparison using month/day logic to handle dates from previous years\n- Family data integration with backup system (export, import, preview, reset)\n- Comprehensive test coverage for family service, IPC handlers, renderer components, and backup operations\n\n### Changed\n\n- Added Family tab to Personal module navigation in AssistantShell\n- Updated backup system to include all family-related tables in export/import/preview/reset operations\n- Updated IPC handler payload contract tests to include family channels"
  },
  {
    "version": "3.3.0",
    "date": "2026-05-26",
    "markdown": "### Added\n\n- Family module for family obligations and relationship management\n- Family member management with contact information and importance markers\n- Family occasions (birthdays, name days, anniversaries, memorials, custom) with yearly recurrence\n- Family obligations (calls, visits, messages, gifts, paperwork, custom) with due date and priority tracking\n- Family summary showing total members, important members, upcoming occasions, open obligations, and overdue obligations\n- Obligation completion tracking with status updates and completion timestamps\n- Yearly occasion calculation that compares by month/day for accurate upcoming event detection\n- Family data integration with backup system (export, import, preview, reset)\n- Comprehensive test coverage for family service, IPC handlers, renderer components, and backup operations\n\n### Changed\n\n- Added Family tab to Personal module navigation in AssistantShell\n- Updated backup system to include all family-related tables in export/import/preview/reset operations\n- Updated IPC handler payload contract tests to include family channels"
  },
  {
    "version": "3.0.1",
    "date": "2026-05-26",
    "markdown": "### Fixed\n\n- Fixed `review day` command to switch to Today module before opening End-of-Day Review, ensuring the review panel is visible from any module\n- Added missing `latest.yml` update manifest to v3.0.0 GitHub release for proper update hygiene"
  },
  {
    "version": "3.0.0",
    "date": "2026-05-26",
    "markdown": "### Changed\n\n- Consolidated daily workflow UI copy to reflect Personal OS branding instead of version-specific references\n- Updated onboarding experience to introduce the app as a local-first personal operating layer\n- Standardized command examples to use consistent `capture`, `find`, and `plan today` commands\n- Enhanced Data Control panel with health check and database optimization buttons\n- Updated success/error messages across workflows for consistency\n- Improved backup action hooks to support health check and optimization operations\n- Updated documentation (README.md, MAINTAINER_GUIDE.md, ARCHITECTURE.md) to reflect Personal OS positioning\n\n### Added\n\n- Database health check UI integration in Data Control panel\n- Database optimization UI integration in Data Control panel\n- Comprehensive health check status reporting with integrity, schema, data, and performance metrics\n- Health check and optimization state management in backup actions hook\n\n### Fixed\n\n- Removed stale version-specific comments from component files\n- Updated command palette and onboarding commands to use consistent terminology\n- Ensured all workflow copy describes the core loop: capture, sort, plan, act, review, search, recover\n\n### Tests\n\n- Updated DataControlPanel tests to cover health check and optimization buttons\n- Added tests for health check and optimization state management\n- All existing tests continue to pass (1031 tests)\n\n### Documentation\n\n- Updated README.md to reflect Personal OS branding and core workflow\n- Updated MAINTAINER_GUIDE.md to reflect Personal OS positioning\n- Updated ARCHITECTURE.md to reflect Personal OS architecture\n- Added Personal OS Core workflow description to README"
  },
  {
    "version": "2.9.0",
    "date": "2026-05-25",
    "markdown": "### Added\n\n- Backup preview with counts and validation before destructive import operations\n- SQLite data health diagnostics (integrity check, schema validation, data analysis, performance metrics)\n- Database optimization functionality (WAL checkpoint, VACUUM, index optimization)\n- Release hygiene check script for pre-release validation\n- AGENTS.md documentation for AI agent development\n- IPC channels for database health checks and optimization\n\n### Changed\n\n- Backup import now uses two-step process: preview first, then confirm with detailed counts\n- Import confirmation dialog shows backup version, export date, and item counts\n- Database health check provides comprehensive diagnostics with recommendations\n- Test databases now use WAL mode for consistency with production\n\n### Tests\n\n- Added 8 comprehensive tests for backup preview functionality\n- Added 8 tests for database health check service\n- Updated backup actions tests for preview integration\n- Updated IPC handler contract tests for new channels"
  },
  {
    "version": "2.8.0",
    "date": "2026-05-25",
    "markdown": "### Added\n\n- Enhanced search ranking system with intelligent scoring for exact matches (100+ points), prefix matches (50+ points), and fuzzy matches\n- Recent items tracking via localStorage to surface frequently accessed items in command palette\n- Saved searches feature to store and reuse common search queries\n- New recall commands: `recent` (shows recent items), `find <query>` (searches with query), `saved searches` (shows saved searches), `open <id>` (opens item by ID)\n- Command palette UI components for displaying recent items and saved searches with section headers and badges\n- CSS styles for command palette sections (`.commandPaletteSection`, `.commandPaletteSectionHeader`, `.commandPaletteSectionList`, `.commandPaletteRecentBadge`, `.commandPaletteSavedBadge`)\n\n### Changed\n\n- Search engine now considers recency boost (+20 points), active/open item boost (+15 points), and completed/done item penalty (-10 points)\n- Command execution accepts additional callback parameters for opening specific item types (notes, tasks, reminders, team tasks)\n- Workspace composition hooks updated to support new search and recall functionality\n- Search results are ranked by confidence score, with high-confidence matches auto-opening and low-confidence matches showing search results\n\n### Tests\n\n- Added 20 comprehensive tests for search ranking system covering exact matches, prefix matches, fuzzy matches, and scoring factors\n- Added 6 tests for recent items tracking (add, get, clear functionality)\n- Added 7 tests for saved searches feature (save, get, delete, clear functionality)\n- Added 3 tests for new recall commands (recent, saved searches, open with exact match, open with no matches, open with low confidence)\n- All verification commands passing: lint, typecheck, test (1031 tests), build"
  },
  {
    "version": "2.7.1",
    "date": "2026-05-25",
    "markdown": "### Fixed\n\n- Quick Capture now refreshes data after successful save, ensuring captured items appear immediately in panels and counters\n- Corrected shortcut documentation to reflect actual binding: Quick Capture uses `Ctrl+Alt+N` / `Command+Alt+N` (not `Ctrl+Shift+N`)\n- Added missing tray menu items for Quick task and Quick reminder to complete Windows tray QA coverage\n\n### Changed\n\n- QuickCaptureDialog now accepts an `onSaved` callback to trigger data refresh after successful capture\n- AssistantShell implements `handleQuickCaptureSaved` to refresh appropriate data slices (notes, tasks, or reminders) based on capture type\n- Success messages now display after data refresh completes for better user feedback\n\n### Tests\n\n- Added test for `onSaved` callback with correct capture type\n- Updated tray-ipc-wiring tests for new Quick task and Quick reminder menu items\n- All verification commands passing: lint, typecheck, test (1002 tests), build, smoke check, preload smoke, npm audit"
  },
  {
    "version": "2.7.0",
    "date": "2026-05-25",
    "markdown": "### Added\n\n- Quick Capture: global capture surface for rapid note, task, reminder, and inbox entry\n- Global shortcut (Cmd/Ctrl+Alt+N) to open Quick Capture dialog from anywhere\n- Tray menu integration with Quick Capture options (Quick note, Quick task, Quick reminder)\n- Command support: `capture`, `capture note <text>`, `capture task <text>`, `capture reminder <text>`\n- QuickCaptureDialog component with type selector and optional fields (due date, priority)\n- Typed text pre-fills from command for streamlined capture workflow\n- onQuickCapture callback through workspace composition for dialog state management\n\n### Changed\n\n- Command execution now routes capture commands to Quick Capture dialog\n- External quick commands from Electron IPC open Quick Capture with appropriate type\n- AssistantCommandDeps type includes onQuickCapture for capture routing\n- TeamDataParams type includes onQuickCapture for workspace wiring\n\n### Tests\n\n- Added 21 renderer tests for QuickCaptureDialog component\n- Updated tray-ipc-wiring tests for capture menu items\n- Updated executeAssistantCommand tests for capture command variants\n- Tests cover type selection, text pre-fill, submission, error handling, and state reset\n- All 998 tests passing"
  },
  {
    "version": "2.6.0",
    "date": "2026-05-25",
    "markdown": "### Added\n\n- End-of-Day Review: daily review workflow showing completed tasks, completed reminders, unfinished items, and captured notes\n- Review Day button in Today strip to trigger end-of-day review\n- \"review day\" command support for keyboard-driven workflow\n- Carry-over actions for unfinished tasks (reschedule to tomorrow) and reminders (snooze to tomorrow)\n- EndOfDayReviewPanel component with categorized sections for different item types\n- deriveEndOfDayReview function to infer today's activity from task, reminder, and note timestamps\n- lastCompletedAt field to BriefItem type for tracking task completion status\n\n### Changed\n\n- BriefItem type now includes optional lastCompletedAt field for accurate completion tracking\n- End-of-day review uses lastCompletedAt timestamp to identify tasks completed today\n- Unfinished items are inferred from due dates and completion status\n\n### Tests\n\n- Added 16 unit tests for deriveEndOfDayReview function\n- Added 14 renderer tests for EndOfDayReviewPanel component\n- Tests cover completion detection, unfinished item identification, carry-over actions, and error handling\n- All 977 tests passing"
  },
  {
    "version": "2.5.0",
    "date": "2026-05-25",
    "markdown": "### Added\n\n- Quick Reschedule: calendar action button for tasks and reminders with preset options (Today, Tomorrow, Next Week, Custom)\n- Batch Snooze: Snooze button for selected reminders with preset options (10 minutes, 1 hour, Tomorrow, Next Week)\n- Enhanced Plan Today panel with scheduling controls for efficient daily planning\n- Dropdown menus for quick scheduling actions with keyboard navigation support\n\n### Changed\n\n- Plan Today panel now includes both completion and scheduling workflows\n- Quick Reschedule uses existing task and reminder update APIs for consistency\n- Batch Snooze only affects selected reminders, leaving tasks unchanged\n- Improved scheduling UX with preset time options for common workflows\n\n### Tests\n\n- Added 18 renderer tests for Quick Reschedule and Batch Snooze functionality\n- Tests cover calendar actions, preset selection, batch operations, and error handling\n- All 951 tests passing"
  },
  {
    "version": "2.4.0",
    "date": "2026-05-25",
    "markdown": "### Added\n\n- Plan Today panel integration into Today module with live queue of overdue tasks, due today reminders, and unsorted notes\n- Batch complete functionality: checkbox selection for tasks and reminders with Select All / Deselect All\n- Complete N Selected action for bulk completing multiple items at once\n- Smart selection logic: only completable items (tasks and reminders) can be selected, notes are excluded\n\n### Changed\n\n- Plan Today queue now integrated into the Today module alongside Daily Command Center\n- Bulk completion uses source IDs for proper API calls\n- Enhanced Plan Today panel with selection state management and batch processing UI\n\n### Tests\n\n- Added 9 renderer tests for batch complete functionality\n- Tests cover checkbox selection, Select All, bulk completion, and state clearing\n- All 933 tests passing"
  },
  {
    "version": "2.3.0",
    "date": "2026-05-25",
    "markdown": "### Added\n\n- Plan Today panel: prioritized queue of overdue tasks, due today reminders, and unsorted notes for daily planning workflow\n- Performance instrumentation (dev-only) for app startup, Today/Inbox render times, and drawer latency\n- Memoization of deriveDailyCommandCenter function for expensive operations\n\n### Changed\n\n- Enhanced type system: added required `id` field to BriefItem for better item tracking and deduplication\n- Improved Plan Today queue derivation with priority-based sorting (overdue > due-today > unsorted)\n\n### Tests\n\n- Added 6 unit tests for derivePlanTodayQueue derivation logic\n- Added 11 renderer tests for PlanTodayPanel component states and actions\n- All existing tests updated to support new BriefItem type requirements"
  },
  {
    "version": "2.2.0",
    "date": "2026-05-25",
    "markdown": "Windows-only manual release. macOS/Linux assets are omitted when packaging validation is not complete.\n\n### Fixed\n\n- Drawer date editing now uses local datetime-local semantics consistently across timezones.\n- Due dates no longer shift when editing local tasks, team tasks, and reminders.\n\n### Tests\n\n- All unit tests passing with timezone-aware date handling."
  },
  {
    "version": "2.1.9",
    "date": "2026-05-22",
    "markdown": "Windows-only manual release. macOS/Linux assets are omitted when packaging validation is not complete.\n\n### Added\n\n- Inbox capture now guides task and reminder captures directly into Today.\n- Today review rows now expose Details, Complete, Snooze, and Open Inbox actions.\n\n### Changed\n\n- Home, Today, and Inbox empty states now guide the daily workflow instead of ending in passive states.\n- Daily Flow navigation now feels continuous across Home, Inbox, Today, and the unified drawer.\n- Inbox row actions and spacing were tightened for better visual density.\n\n### Fixed\n\n- Undated captured tasks now appear in Today Context.\n- Captured reminders are deduplicated in Today review.\n- Electron main-process build output now matches the packaged app entry contract.\n- Inbox capture controls remain visible after CSS token normalization.\n\n### Security\n\n- Security audit completed with zero critical, high, or medium findings.\n\n### Tests\n\n- Full local gates passed.\n- Electron manual QA passed for Inbox to Today capture, task completion, reminder snooze, note capture, empty states, and narrow viewport layout."
  },
  {
    "version": "2.1.8",
    "date": "2026-05-21",
    "markdown": "Windows-only manual release. macOS/Linux assets are omitted when packaging validation is not complete.\n\n### Fixed\n\n- Windows desktop and Start menu shortcuts now use the PersonalAssistant icon even when executable resource editing is disabled.\n\n### Tests\n\n- NSIS installer build and smoke check verified shortcut icon packaging."
  },
  {
    "version": "2.1.7",
    "date": "2026-05-21",
    "markdown": "Windows-only manual release. macOS/Linux assets are omitted when packaging validation is not complete.\n\n### Added\n\n- Corporate security mode with policy file enforcement for managed deployments.\n- Outbound network guard with host allowlisting for controlled external connections.\n- Encrypted backup export in corporate mode using OS-level encryption.\n- Policy controls for backup export/import, external URLs, and secret storage requirements.\n- Content Security Policy (CSP) generation from policy in corporate mode.\n- Security audit scripts: SBOM generation, npm audit, and release evidence collection.\n- Windows code signing support via electron-builder environment variables.\n- Corporate security documentation: IT Review Packet, database-at-rest strategy, and updated corporate mode guide.\n- Release notes panel that shows once per installed version.\n\n### Changed\n\n- Dashboard polish with improved visual hierarchy and spacing.\n- Light theme distinction for better readability.\n- Windows icon identity fix for consistent taskbar and title bar appearance.\n- Policy file ACL validation with fail-closed behavior in corporate mode.\n- Secret storage fail-closed behavior when OS encryption is unavailable.\n\n### Security\n\n- All secrets (AI API keys, Home Assistant tokens, Supabase keys) encrypted via OS safeStorage.\n- Backup export excludes secret settings and imports reject secret fields.\n- Outbound guard enforces host allowlisting at service layer and CSP layer.\n- Policy file validation prevents user-writable policy files in corporate mode.\n- Database-at-rest strategy documented with OS-level encryption recommendations.\n\n### Tests\n\n- All 868 unit tests passing.\n- Lint, typecheck, and production builds all passing.\n- Security verification suite (audit, SBOM, release evidence) passing."
  },
  {
    "version": "2.1.6",
    "date": "2026-05-20",
    "markdown": "Windows-only manual release. macOS/Linux assets are omitted when packaging validation is not complete.\n\n### Fixed\n\n- First-run onboarding now works with the new module-tab layout.\n- Note creation step switches to Memos module before showing the note form.\n- Reminder creation step switches to Reminders module before showing the reminder form.\n- Completed onboarding lands on the default Home layout (Calendar left, Command right).\n- Electron E2E tests for first-run onboarding now pass with the updated layout.\n\n### Tests\n\n- All 24 Electron E2E tests passing.\n- Browser E2E, unit suite, typecheck, lint, and production builds all passing."
  },
  {
    "version": "2.1.5",
    "date": "2026-05-20",
    "markdown": "Windows-only manual release. macOS/Linux assets are omitted when packaging validation is not complete.\n\n### Changed\n\n- Desk UI now opens to a focused two-column Home dashboard: Calendar on the left, Command input on the right.\n- Top module buttons (Home, Today, Inbox, Memos, Reminders, Tasks, Automations) replace the previous tab strip.\n- Home dashboard is the default view; clicking a module button shows that focused module view.\n- Calendar is always visible in the Home dashboard; separate Calendar tab removed.\n- Top count chips are now clickable and navigate to their corresponding modules.\n\n### Fixed\n\n- Renderer load stability when Electron preload bridge is unavailable or partial.\n- Typed preload helper no longer leaks `unknown` return types into renderer code.\n\n### Tests\n\n- Preload smoke test, E2E Home layout navigation test, unit suite, typecheck, lint, and production builds all passing."
  },
  {
    "version": "2.1.4",
    "date": "2026-05-19",
    "markdown": "Security hardening and Electron upgrade. This is a Windows-only manual release; macOS/Linux assets are omitted when packaging validation is not complete.\n\n### Added\n\n- ISO 27001 readiness documentation pack under `docs/security/`, including control mapping, risk register, asset inventory, operational controls, and Greek management summary.\n- v2.1.4 release evidence checklist with verification results and installer checksum.\n\n### Changed\n\n- Upgraded Electron from 35.0.0 to 41.0.0, electron-builder from 25.1.8 to 26.8.1, and better-sqlite3 from 11.8.1 to 12.10.0.\n- Added `npm audit --audit-level=high` as a documented release security gate.\n- Removed dependency overrides that are no longer needed after the Electron upgrade.\n\n### Security\n\n- Fail-closed secret storage now refuses to store AI API keys, Home Assistant tokens, and Supabase session tokens when OS encryption is unavailable.\n- Backup export excludes secret settings, and backup import rejects backups containing secret fields.\n- Renderer error persistence redacts secrets before logs are stored.\n- Packaged Electron runtime uses sandboxing and a hardened Content Security Policy.\n\n### Fixed\n\n- AI provider errors now surface as real provider errors instead of generic command failures."
  },
  {
    "version": "2.1.3",
    "date": "2026-05-18",
    "markdown": "Team Projects setup hotfix. This is a Windows-only manual release; macOS/Linux assets are omitted when packaging validation is not complete.\n\n### Changed\n\n- Replaced the Team Projects unavailable dead end with a beginner-friendly in-app setup flow.\n- Added release-time hosted backend bundling so hosted Team Projects builds can ask users only for a display name.\n- Updated Team Projects setup documentation around hosted builds and app-guided setup."
  },
  {
    "version": "2.1.2",
    "date": "2026-05-18",
    "markdown": "Personal OS app workflow hardening. This is a Windows-only manual release; macOS/Linux assets are omitted when packaging validation is not complete.\n\n### Added\n\n- Editable local reminders from the unified drawer.\n- Team tasks in Unified Inbox, Daily Command Center, Command Palette, Today Strip, and the unified drawer.\n- Calendar quick-create flows for tasks and reminders.\n- Automation rule visibility and focus handoff from Desk into Household.\n- Send local tasks to Team Projects from Inbox.\n\n### Changed\n\n- Centralized team realtime refresh through a reusable subscription helper.\n- Opened notes, tasks, reminders, and team tasks from Command Palette through the unified drawer.\n- Made Windows manual release the active documented release path.\n- Removed stale brief panels after Daily Command Center became the active brief surface.\n\n### Fixed\n\n- Preserved task metadata when editing local task details from the unified drawer.\n- Hardened Calendar Quick Create date handling and test determinism.\n- Hardened Data Control backup, import, and reset button states and renderer coverage."
  },
  {
    "version": "2.1.1",
    "date": "2026-05-15",
    "markdown": "Personal OS v3 integration hardening and manual release reliability. This is a Windows-only manual release; macOS/Linux assets are omitted when packaging validation is not complete.\n\n### Added\n\n- Personal OS v3 integration: Unified Inbox panel with quick capture for notes, tasks, and reminders.\n- WorkItemDetailDrawer: unified detail drawer for viewing and editing work items from Inbox and Daily Command Center.\n- Daily Command Center drawer integration: clickable item labels open the unified detail drawer.\n- Windows-only manual release documentation in RELEASING.md.\n\n### Changed\n\n- Removed stale version-specific comments from codebase.\n- Updated README.md to clarify that GitHub Actions is not required for releases.\n- Updated APP_AUDIT_2026-05-15.md to reflect v3 stack and 616 tests passing.\n\n### Fixed\n\n- No mojibake found in user-facing text; only acceptable em-dashes in comments and theme names remain.\n- Layouts for DCC, Inbox, and detail drawer are properly responsive with no overflow issues."
  },
  {
    "version": "2.1.0",
    "date": "2026-05-15",
    "markdown": "Team Projects UX and setup release. Friendly display-name-first setup, shared task editor, task board filters, realtime IPC cleanup, and visual hardening.\n\n### Added\n\n- Friendly Team Projects setup: display-name-first flow with optional advanced self-hosted backend configuration.\n- Hosted backend support via `TEAM_PROJECTS_SUPABASE_URL` and `TEAM_PROJECTS_SUPABASE_ANON_KEY` environment variables.\n- Shared task editor with full task fields (title, notes, due date, priority, recurrence, assignee).\n- Task board filters by project and status.\n- Realtime IPC cleanup with debounced refresh and per-workspace channel management.\n- `teamSetDisplayName` IPC method for display-name-only configuration.\n\n### Changed\n\n- Team Projects copy uses user-facing terms (workspace, invite code, shared tasks) instead of technical terms (Supabase, anon key, backend).\n- Performance optimization: project lookup map and memoized filtered tasks to avoid repeated find calls.\n- Visual hardening: added proper spacing to workspace items with dedicated CSS.\n- Security verification: confirmed no Supabase credentials exposed in normal UI; all team IPC handlers validate with Zod; trusted sender checks in place.\n\n### Fixed\n\n- Workspace items now have proper spacing between them."
  },
  {
    "version": "2.0.0",
    "date": "2026-05-13",
    "markdown": "First \"stable\" milestone after the rapid 1.4.x → 1.7.x iteration phase. No breaking user-facing behavior versus 1.7.1; the major bump signals the end of that exploration phase and the start of a more disciplined release cadence (see `RELEASING.md`). Skips over a stray `v2.1.8` test tag that was never publicly distributed.\n\n### Added\n\n- `docs/ARCHITECTURE.md` — high-level architecture reference for contributors.\n- `RELEASING.md` — versioning and release discipline going forward.\n- App-window IPC handler with dedicated security tests (`window.security.test.ts`, `appWindow.handlers.test.ts`).\n- Custom theme editor with expanded appearance tokens, contrast guidance, and a dedicated test suite.\n- About panel updates with clearer version visibility.\n- Handler payload contract tests for the renderer/main IPC boundary.\n\n### Changed\n\n- `useAssistantWorkspace` refactored: type definitions extracted into `src/renderer/hooks/workspace/workspaceTypes.ts`; composition hooks consolidated. No behavior change.\n- `release-assets` script and tests tightened.\n- Backup service hardened.\n- Small fixes to command palette and search engine.\n\n### Removed\n\n- Unused layout components: `AppHeader`, `WelcomeBar`.\n\n### Fixed\n\n- E2E test specs aligned with the current desk UI (web + Electron suites)."
  },
  {
    "version": "1.7.1",
    "date": "2026-05-13",
    "markdown": "### Added\n\n- macOS `.zip` requirement in release validation.\n\n### Changed\n\n- Release pipeline publishes directly without using GitHub Actions artifacts (saves storage quota).\n- UI text normalization (mojibake removal, copy consistency).\n- Updated release docs covering macOS release behavior.\n\n### Fixed\n\n- Stabilized v1.7.1 source sync between worker tooling and tracked sources."
  },
  {
    "version": "1.7.0",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Data control and backup: export notes, tasks, reminders, automations, and settings to JSON; import with conflict handling; local backup reminder setting."
  },
  {
    "version": "1.6.5",
    "date": "2026-05-12",
    "markdown": "Windows installer release rolling up 1.6.1 – 1.6.4."
  },
  {
    "version": "1.6.4",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Automation builder upgrade: trigger / action / review step layout, enable-disable toggle per rule, last-run status, duplicate rule, test-run button."
  },
  {
    "version": "1.6.3",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Agenda list view alongside the month calendar.\n- Tasks with due dates rendered alongside reminders.\n- Today / Tomorrow / This week filters.\n- Click-to-create reminder/task from a selected day."
  },
  {
    "version": "1.6.2",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Note archive and task archive views.\n- Bulk complete for selected tasks.\n- Inline task priority editing.\n- Pin/unpin notes from search results.\n- Undo for task complete, reminder done, and note archive."
  },
  {
    "version": "1.6.1",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Global command palette across notes, tasks, reminders, automations, settings, and Home Assistant actions.\n- Structured search results with keyboard navigation."
  },
  {
    "version": "1.6.0",
    "date": "2026-05-12",
    "markdown": "Windows installer release rolling up 1.5.6 – 1.5.9."
  },
  {
    "version": "1.5.9",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Today strip with overdue / due-today / reminders / notes / automations counts.\n- Quick filters from the strip into Tasks, Reminders, Notes, Automations.\n\n### Changed\n\n- Improved empty states across panels.\n- Standardized panel headers, action rows, list rows, and timestamps.\n\n### Removed\n\n- Remaining mojibake and playful labels."
  },
  {
    "version": "1.5.8",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Density preference: Comfortable, Compact, Spacious.\n- Panel radius preference: Sharp, Soft, Rounded.\n- Optional shadows toggle and glass-blur toggle.\n- DCC section preference (one secondary vs all secondary sections)."
  },
  {
    "version": "1.5.7",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Appearance panel in the top toolbar with full custom theme editor: per-token color inputs, reset, duplicate preset, save custom theme, JSON import/export, contrast warnings."
  },
  {
    "version": "1.5.6",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Theme token foundation: typed `ThemeTokenKey`, `ThemePreset`, and `CustomTheme`. Built-in presets (Glass, Paper, Obsidian, Fog, Deep Blue) plus Corporate. Custom overrides applied via CSS variables on `documentElement`."
  },
  {
    "version": "1.5.5",
    "date": "2026-05-11",
    "markdown": "Final minimal corporate pass. Version bump rolling up 1.5.2 – 1.5.4."
  },
  {
    "version": "1.5.4",
    "date": "2026-05-11",
    "markdown": "### Changed\n\n- Corporate automation polish."
  },
  {
    "version": "1.5.3",
    "date": "2026-05-11",
    "markdown": "### Changed\n\n- Friendly workflow clarity pass."
  },
  {
    "version": "1.5.2",
    "date": "2026-05-11",
    "markdown": "### Changed\n\n- Minimal corporate desk baseline."
  },
  {
    "version": "1.5.0",
    "date": "2026-05-08",
    "markdown": "### Added\n\n- Daily command center with navigation actions and visual hierarchy.\n- Local task automations.\n- Strengthened local-first desk experience.\n\n### Changed\n\n- Hardened release packaging.\n\n### Fixed\n\n- Improved automation retry logs."
  },
  {
    "version": "1.4.3",
    "date": "2026-05-07",
    "markdown": "### Added\n\n- Worker activity handoff log.\n- Comprehensive worker handoff docs.\n\n### Changed\n\n- Enforced repository line endings.\n- Tidied quality baseline.\n- Documented Electron 42 upgrade failure (better-sqlite3 incompatibility).\n\n### Fixed\n\n- Hardened away-brief behavior.\n- Strengthened away-brief and security test coverage."
  }
];

export function getReleaseNote(version: string): ReleaseNote | undefined {
  return releaseNotes.find((note) => note.version === version);
}

export function getLatestReleaseNote(): ReleaseNote | undefined {
  return releaseNotes[0];
}
