// This file is auto-generated by scripts/generate-release-notes.mjs
// Do not edit manually.

export type ReleaseNote = {
  version: string;
  date: string;
  markdown: string;
};

export const releaseNotes: ReleaseNote[] = [
  {
    "version": "2.1.7",
    "date": "2026-05-21",
    "markdown": "Windows-only manual release. macOS/Linux assets are omitted due to GitHub Actions budget constraints.\n\n### Added\n\n- Corporate security mode with policy file enforcement for managed deployments.\n- Outbound network guard with host allowlisting for controlled external connections.\n- Encrypted backup export in corporate mode using OS-level encryption.\n- Policy controls for backup export/import, external URLs, and secret storage requirements.\n- Content Security Policy (CSP) generation from policy in corporate mode.\n- Security audit scripts: SBOM generation, npm audit, and release evidence collection.\n- Windows code signing support via electron-builder environment variables.\n- Corporate security documentation: IT Review Packet, database-at-rest strategy, and updated corporate mode guide.\n- Release notes panel that shows once per installed version.\n\n### Changed\n\n- Dashboard polish with improved visual hierarchy and spacing.\n- Light theme distinction for better readability.\n- Windows icon identity fix for consistent taskbar and title bar appearance.\n- Policy file ACL validation with fail-closed behavior in corporate mode.\n- Secret storage fail-closed behavior when OS encryption is unavailable.\n\n### Security\n\n- All secrets (AI API keys, Home Assistant tokens, Supabase keys) encrypted via OS safeStorage.\n- Backup export excludes secret settings and imports reject secret fields.\n- Outbound guard enforces host allowlisting at service layer and CSP layer.\n- Policy file validation prevents user-writable policy files in corporate mode.\n- Database-at-rest strategy documented with OS-level encryption recommendations.\n\n### Tests\n\n- All 868 unit tests passing.\n- Lint, typecheck, and production builds all passing.\n- Security verification suite (audit, SBOM, release evidence) passing."
  },
  {
    "version": "2.1.6",
    "date": "2026-05-20",
    "markdown": "Windows-only manual release. macOS/Linux assets are omitted due to GitHub Actions budget constraints.\n\n### Fixed\n\n- First-run onboarding now works with the new module-tab layout.\n- Note creation step switches to Memos module before showing the note form.\n- Reminder creation step switches to Reminders module before showing the reminder form.\n- Completed onboarding lands on the default Home layout (Calendar left, Command right).\n- Electron E2E tests for first-run onboarding now pass with the updated layout.\n\n### Tests\n\n- All 24 Electron E2E tests passing.\n- Browser E2E, unit suite, typecheck, lint, and production builds all passing."
  },
  {
    "version": "2.1.5",
    "date": "2026-05-20",
    "markdown": "Windows-only manual release. macOS/Linux assets are omitted due to GitHub Actions budget constraints.\n\n### Changed\n\n- Desk UI now opens to a focused two-column Home dashboard: Calendar on the left, Command input on the right.\n- Top module buttons (Home, Today, Inbox, Memos, Reminders, Tasks, Automations) replace the previous tab strip.\n- Home dashboard is the default view; clicking a module button shows that focused module view.\n- Calendar is always visible in the Home dashboard; separate Calendar tab removed.\n- Top count chips are now clickable and navigate to their corresponding modules.\n\n### Fixed\n\n- Renderer load stability when Electron preload bridge is unavailable or partial.\n- Typed preload helper no longer leaks `unknown` return types into renderer code.\n\n### Tests\n\n- Preload smoke test, E2E Home layout navigation test, unit suite, typecheck, lint, and production builds all passing."
  },
  {
    "version": "2.1.4",
    "date": "2026-05-19",
    "markdown": "Security hardening and Electron upgrade. This is a Windows-only manual release; macOS/Linux assets are omitted due to GitHub Actions budget constraints.\n\n### Added\n\n- ISO 27001 readiness documentation pack under `docs/security/`, including control mapping, risk register, asset inventory, operational controls, and Greek management summary.\n- v2.1.4 release evidence checklist with verification results and installer checksum.\n\n### Changed\n\n- Upgraded Electron from 35.0.0 to 41.0.0, electron-builder from 25.1.8 to 26.8.1, and better-sqlite3 from 11.8.1 to 12.10.0.\n- Added `npm audit --audit-level=high` as a documented release security gate.\n- Removed dependency overrides that are no longer needed after the Electron upgrade.\n\n### Security\n\n- Fail-closed secret storage now refuses to store AI API keys, Home Assistant tokens, and Supabase session tokens when OS encryption is unavailable.\n- Backup export excludes secret settings, and backup import rejects backups containing secret fields.\n- Renderer error persistence redacts secrets before logs are stored.\n- Packaged Electron runtime uses sandboxing and a hardened Content Security Policy.\n\n### Fixed\n\n- AI provider errors now surface as real provider errors instead of generic command failures."
  },
  {
    "version": "2.1.3",
    "date": "2026-05-18",
    "markdown": "Team Projects setup hotfix. This is a Windows-only manual release; macOS/Linux assets are omitted due to GitHub Actions budget constraints.\n\n### Changed\n\n- Replaced the Team Projects unavailable dead end with a beginner-friendly in-app setup flow.\n- Added release-time hosted backend bundling so hosted Team Projects builds can ask users only for a display name.\n- Updated Team Projects setup documentation around hosted builds and app-guided setup."
  },
  {
    "version": "2.1.2",
    "date": "2026-05-18",
    "markdown": "Personal OS app workflow hardening. This is a Windows-only manual release; macOS/Linux assets are omitted due to GitHub Actions budget constraints.\n\n### Added\n\n- Editable local reminders from the unified drawer.\n- Team tasks in Unified Inbox, Daily Command Center, Command Palette, Today Strip, and the unified drawer.\n- Calendar quick-create flows for tasks and reminders.\n- Automation rule visibility and focus handoff from Desk into Household.\n- Send local tasks to Team Projects from Inbox.\n\n### Changed\n\n- Centralized team realtime refresh through a reusable subscription helper.\n- Opened notes, tasks, reminders, and team tasks from Command Palette through the unified drawer.\n- Made Windows manual release the active documented release path.\n- Removed stale brief panels after Daily Command Center became the active brief surface.\n\n### Fixed\n\n- Preserved task metadata when editing local task details from the unified drawer.\n- Hardened Calendar Quick Create date handling and test determinism.\n- Hardened Data Control backup, import, and reset button states and renderer coverage."
  },
  {
    "version": "2.1.1",
    "date": "2026-05-15",
    "markdown": "Personal OS v3 integration hardening and manual release reliability. This is a Windows-only manual release; macOS/Linux assets are omitted due to GitHub Actions budget constraints.\n\n### Added\n\n- Personal OS v3 integration: Unified Inbox panel with quick capture for notes, tasks, and reminders.\n- WorkItemDetailDrawer: unified detail drawer for viewing and editing work items from Inbox and Daily Command Center.\n- Daily Command Center drawer integration: clickable item labels open the unified detail drawer.\n- Windows-only manual release documentation in RELEASING.md.\n\n### Changed\n\n- Removed stale version-specific comments from codebase.\n- Updated README.md to clarify that GitHub Actions is not required for releases.\n- Updated APP_AUDIT_2026-05-15.md to reflect v3 stack and 616 tests passing.\n\n### Fixed\n\n- No mojibake found in user-facing text; only acceptable em-dashes in comments and theme names remain.\n- Layouts for DCC, Inbox, and detail drawer are properly responsive with no overflow issues."
  },
  {
    "version": "2.1.0",
    "date": "2026-05-15",
    "markdown": "Team Projects UX and setup release. Friendly display-name-first setup, shared task editor, task board filters, realtime IPC cleanup, and visual hardening.\n\n### Added\n\n- Friendly Team Projects setup: display-name-first flow with optional advanced self-hosted backend configuration.\n- Hosted backend support via `TEAM_PROJECTS_SUPABASE_URL` and `TEAM_PROJECTS_SUPABASE_ANON_KEY` environment variables.\n- Shared task editor with full task fields (title, notes, due date, priority, recurrence, assignee).\n- Task board filters by project and status.\n- Realtime IPC cleanup with debounced refresh and per-workspace channel management.\n- `teamSetDisplayName` IPC method for display-name-only configuration.\n\n### Changed\n\n- Team Projects copy uses user-facing terms (workspace, invite code, shared tasks) instead of technical terms (Supabase, anon key, backend).\n- Performance optimization: project lookup map and memoized filtered tasks to avoid repeated find calls.\n- Visual hardening: added proper spacing to workspace items with dedicated CSS.\n- Security verification: confirmed no Supabase credentials exposed in normal UI; all team IPC handlers validate with Zod; trusted sender checks in place.\n\n### Fixed\n\n- Workspace items now have proper spacing between them."
  },
  {
    "version": "2.0.0",
    "date": "2026-05-13",
    "markdown": "First \"stable\" milestone after the rapid 1.4.x → 1.7.x iteration phase. No breaking user-facing behavior versus 1.7.1; the major bump signals the end of that exploration phase and the start of a more disciplined release cadence (see `RELEASING.md`). Skips over a stray `v2.1.8` test tag that was never publicly distributed.\n\n### Added\n\n- `docs/ARCHITECTURE.md` — high-level architecture reference for contributors.\n- `RELEASING.md` — versioning and release discipline going forward.\n- App-window IPC handler with dedicated security tests (`window.security.test.ts`, `appWindow.handlers.test.ts`).\n- Custom theme editor with expanded appearance tokens, contrast guidance, and a dedicated test suite.\n- About panel updates with clearer version visibility.\n- Handler payload contract tests for the renderer/main IPC boundary.\n\n### Changed\n\n- `useAssistantWorkspace` refactored: type definitions extracted into `src/renderer/hooks/workspace/workspaceTypes.ts`; composition hooks consolidated. No behavior change.\n- `release-assets` script and tests tightened.\n- Backup service hardened.\n- Small fixes to command palette and search engine.\n\n### Removed\n\n- Unused layout components: `AppHeader`, `WelcomeBar`.\n\n### Fixed\n\n- E2E test specs aligned with the current desk UI (web + Electron suites)."
  },
  {
    "version": "1.7.1",
    "date": "2026-05-13",
    "markdown": "### Added\n\n- macOS `.zip` requirement in release validation.\n\n### Changed\n\n- Release pipeline publishes directly without using GitHub Actions artifacts (saves storage quota).\n- UI text normalization (mojibake removal, copy consistency).\n- Updated release docs covering macOS and `PUBLIC_RELEASE_TOKEN` behavior.\n\n### Fixed\n\n- Stabilized v1.7.1 source sync between worker tooling and tracked sources."
  },
  {
    "version": "1.7.0",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Data control and backup: export notes, tasks, reminders, automations, and settings to JSON; import with conflict handling; local backup reminder setting."
  },
  {
    "version": "1.6.5",
    "date": "2026-05-12",
    "markdown": "Windows installer release rolling up 1.6.1 – 1.6.4."
  },
  {
    "version": "1.6.4",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Automation builder upgrade: trigger / action / review step layout, enable-disable toggle per rule, last-run status, duplicate rule, test-run button."
  },
  {
    "version": "1.6.3",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Agenda list view alongside the month calendar.\n- Tasks with due dates rendered alongside reminders.\n- Today / Tomorrow / This week filters.\n- Click-to-create reminder/task from a selected day."
  },
  {
    "version": "1.6.2",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Note archive and task archive views.\n- Bulk complete for selected tasks.\n- Inline task priority editing.\n- Pin/unpin notes from search results.\n- Undo for task complete, reminder done, and note archive."
  },
  {
    "version": "1.6.1",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Global command palette across notes, tasks, reminders, automations, settings, and Home Assistant actions.\n- Structured search results with keyboard navigation."
  },
  {
    "version": "1.6.0",
    "date": "2026-05-12",
    "markdown": "Windows installer release rolling up 1.5.6 – 1.5.9."
  },
  {
    "version": "1.5.9",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Today strip with overdue / due-today / reminders / notes / automations counts.\n- Quick filters from the strip into Tasks, Reminders, Notes, Automations.\n\n### Changed\n\n- Improved empty states across panels.\n- Standardized panel headers, action rows, list rows, and timestamps.\n\n### Removed\n\n- Remaining mojibake and playful labels."
  },
  {
    "version": "1.5.8",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Density preference: Comfortable, Compact, Spacious.\n- Panel radius preference: Sharp, Soft, Rounded.\n- Optional shadows toggle and glass-blur toggle.\n- DCC section preference (one secondary vs all secondary sections)."
  },
  {
    "version": "1.5.7",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Appearance panel in the top toolbar with full custom theme editor: per-token color inputs, reset, duplicate preset, save custom theme, JSON import/export, contrast warnings."
  },
  {
    "version": "1.5.6",
    "date": "2026-05-12",
    "markdown": "### Added\n\n- Theme token foundation: typed `ThemeTokenKey`, `ThemePreset`, and `CustomTheme`. Built-in presets (Glass, Paper, Obsidian, Fog, Deep Blue) plus Corporate. Custom overrides applied via CSS variables on `documentElement`."
  },
  {
    "version": "1.5.5",
    "date": "2026-05-11",
    "markdown": "Final minimal corporate pass. Version bump rolling up 1.5.2 – 1.5.4."
  },
  {
    "version": "1.5.4",
    "date": "2026-05-11",
    "markdown": "### Changed\n\n- Corporate automation polish."
  },
  {
    "version": "1.5.3",
    "date": "2026-05-11",
    "markdown": "### Changed\n\n- Friendly workflow clarity pass."
  },
  {
    "version": "1.5.2",
    "date": "2026-05-11",
    "markdown": "### Changed\n\n- Minimal corporate desk baseline."
  },
  {
    "version": "1.5.0",
    "date": "2026-05-08",
    "markdown": "### Added\n\n- Daily command center with navigation actions and visual hierarchy.\n- Local task automations.\n- Strengthened local-first desk experience.\n\n### Changed\n\n- Hardened release packaging.\n\n### Fixed\n\n- Improved automation retry logs."
  },
  {
    "version": "1.4.3",
    "date": "2026-05-07",
    "markdown": "### Added\n\n- Worker activity handoff log.\n- Comprehensive worker handoff docs.\n\n### Changed\n\n- Enforced repository line endings.\n- Tidied quality baseline.\n- Documented Electron 42 upgrade failure (better-sqlite3 incompatibility).\n\n### Fixed\n\n- Hardened away-brief behavior.\n- Strengthened away-brief and security test coverage."
  }
];

export function getReleaseNote(version: string): ReleaseNote | undefined {
  return releaseNotes.find((note) => note.version === version);
}

export function getLatestReleaseNote(): ReleaseNote | undefined {
  return releaseNotes[0];
}
