/**
 * IPC invoke channel names (must match `ipcMain.handle` and `ipcRenderer.invoke`).
 *
 * **Preload:** literals are copied into `preload-ipc-literals.generated.ts` by
 * `scripts/generate-preload-ipc.mjs` (run from `build:main` / `test`). Preload imports that file
 * only (not this module) to avoid runtime resolution issues. After editing, run codegen or
 * `npm test` - `preload-channels.test.ts` asserts parity.
 */
export const IpcInvoke = {
  notesList: "notes:list",
  notesCreate: "notes:create",
  notesUpdate: "notes:update",
  notesDelete: "notes:delete",
  remindersList: "reminders:list",
  remindersCreate: "reminders:create",
  remindersUpdate: "reminders:update",
  remindersComplete: "reminders:complete",
  remindersDelete: "reminders:delete",
  remindersSnooze: "reminders:snooze",
  tasksList: "tasks:list",
  tasksCreate: "tasks:create",
  tasksUpdate: "tasks:update",
  tasksComplete: "tasks:complete",
  tasksDelete: "tasks:delete",
  haConfigure: "ha:configure",
  haGetConfig: "ha:getConfig",
  haTest: "ha:test",
  haRefresh: "ha:refresh",
  haListDevices: "ha:listDevices",
  haToggle: "ha:toggle",
  settingsGetAssistant: "settings:getAssistant",
  settingsSetAssistantName: "settings:setAssistantName",
  settingsSetUserPreferredName: "settings:setUserPreferredName",
  settingsGetSecurityPolicy: "settings:getSecurityPolicy",
  automationLogs: "automation:logs",
  automationRulesList: "automation:rules:list",
  automationRulesCreate: "automation:rules:create",
  automationRulesDelete: "automation:rules:delete",
  automationRulesSetEnabled: "automation:rules:setEnabled",
  automationRulesDuplicate: "automation:rules:duplicate",
  automationRulesTestRun: "automation:rules:testRun",
  dataExport: "data:export",
  dataImport: "data:import",
  dataImportPreview: "data:import:preview",
  dataReset: "data:reset",
  dbHealthCheck: "db:healthCheck",
  dbOptimize: "db:optimize",
  rendererLogError: "renderer:logError",
  appOpenHouseholdWindow: "app:openHouseholdWindow",
  appFocusDeskWindow: "app:focusDeskWindow",
  appHideDeskWindow: "app:hideDeskWindow",
  appOpenBugReport: "app:openBugReport",
  testSetHaFetchOverride: "test:setHaFetchOverride",
  testSetAutomationActionOverride: "test:setAutomationActionOverride",
  teamGetConfig: "team:getConfig",
  teamSetConfig: "team:setConfig",
  teamSetDisplayName: "team:setDisplayName",
  teamClearConfig: "team:clearConfig",
  teamWorkspacesCreate: "team:workspaces:create",
  teamWorkspacesJoin: "team:workspaces:join",
  teamWorkspacesList: "team:workspaces:list",
  teamWorkspacesSetActive: "team:workspaces:setActive",
  teamProjectsCreate: "team:projects:create",
  teamProjectsList: "team:projects:list",
  teamTasksCreate: "team:tasks:create",
  teamTasksList: "team:tasks:list",
  teamTasksUpdate: "team:tasks:update",
  teamRealtimeStart: "team:realtime:start",
  teamRealtimeStop: "team:realtime:stop",
  aiGetConfig: "ai:getConfig",
  aiSetKey: "ai:setKey",
  aiClearKey: "ai:clearKey",
  aiTestKey: "ai:testKey",
  aiChat: "ai:chat",
  financeBillsList: "finance:bills:list",
  financeBillsCreate: "finance:bills:create",
  financeBillsUpdate: "finance:bills:update",
  financeBillsDelete: "finance:bills:delete",
  financeBillsMarkPaid: "finance:bills:markPaid",
  financeExpensesList: "finance:expenses:list",
  financeExpensesCreate: "finance:expenses:create",
  financeExpensesUpdate: "finance:expenses:update",
  financeExpensesDelete: "finance:expenses:delete",
  financeSummaryGet: "finance:summary:get",
  carVehiclesList: "car:vehicles:list",
  carVehiclesCreate: "car:vehicles:create",
  carVehiclesUpdate: "car:vehicles:update",
  carVehiclesDelete: "car:vehicles:delete",
  carFuelList: "car:fuel:list",
  carFuelCreate: "car:fuel:create",
  carFuelUpdate: "car:fuel:update",
  carFuelDelete: "car:fuel:delete",
  carMaintenanceList: "car:maintenance:list",
  carMaintenanceCreate: "car:maintenance:create",
  carMaintenanceUpdate: "car:maintenance:update",
  carMaintenanceDelete: "car:maintenance:delete",
  carRecurringBillsList: "car:recurringBills:list",
  carRecurringBillsCreate: "car:recurringBills:create",
  carRecurringBillsUpdate: "car:recurringBills:update",
  carRecurringBillsMarkPaid: "car:recurringBills:markPaid",
  carRecurringBillsDelete: "car:recurringBills:delete",
  carMileageList: "car:mileage:list",
  carMileageCreate: "car:mileage:create",
  carMileageUpdate: "car:mileage:update",
  carMileageDelete: "car:mileage:delete",
  carServiceRemindersList: "car:serviceReminders:list",
  carServiceRemindersCreate: "car:serviceReminders:create",
  carServiceRemindersUpdate: "car:serviceReminders:update",
  carServiceRemindersComplete: "car:serviceReminders:complete",
  carServiceRemindersDelete: "car:serviceReminders:delete",
  familyMembersList: "family:members:list",
  familyMembersCreate: "family:members:create",
  familyMembersUpdate: "family:members:update",
  familyMembersDelete: "family:members:delete",
  familyOccasionsList: "family:occasions:list",
  familyOccasionsCreate: "family:occasions:create",
  familyOccasionsUpdate: "family:occasions:update",
  familyOccasionsDelete: "family:occasions:delete",
  familyObligationsList: "family:obligations:list",
  familyObligationsCreate: "family:obligations:create",
  familyObligationsUpdate: "family:obligations:update",
  familyObligationsComplete: "family:obligations:complete",
  familyObligationsDelete: "family:obligations:delete",
  familySummaryGet: "family:summary:get"
} as const;

/** Channels the main process pushes to the renderer (`webContents.send` / `ipcRenderer.on`). */
export const IpcRendererEvent = {
  remindersUpdated: "reminders:updated",
  command: "command",
  showAbout: "showAbout",
  teamDataUpdated: "team:dataUpdated"
} as const;
